### ISSUE TITLE
The datasize of Shuffle read and write  is much larger

### ISSUE THREAD

**Issue by zuoliwei** [Tencent/Firestorm#100]
hello, when I run the wordcount tesk  in Hibench ,datasize is 5g,  I found that the datasize of shuffle write and read using  firestorm(Memory_HDFS mode) is much larger than using the external shuffle service with the same spark parameters
![image](https://user-images.githubusercontent.com/58681446/159285300-49baf9cb-393c-4bbc-a924-16b31d88d021.png)

![image](https://user-images.githubusercontent.com/58681446/159285859-772b7343-d925-48b7-8293-96d67059606c.png)
 
could you please analyze why it happened

**Comment by colinmjj** [comment]
@zuoliwei currently, Firestorm haven't function of map side combine, maybe the problem is caused by this.
with Firestorm, you can get benefit in following situation:
1. Support spark on K8S better
2. Performance improvement when random IO seriously with ESS
In your test case, I think performance degradation with Firestorm is in expectation

**Comment by zuoliwei** [comment]
OK ，I  got it   thank you
